spring.application.name=shop

# Giới hạn kích thước file upload
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB

# Thư mục lưu ảnh tự định nghĩa
file.upload-dir=uploads/